/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general-purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    checkstyle
    java
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("data"))
        }
        resources {
            setSrcDirs(listOf("data"))
        }
    }
}

tasks.withType(Checkstyle::class.java).configureEach {
    minHeapSize = "200m"
    maxHeapSize = "4g"
    maxWarnings = 0  // Fail on any warning
    maxErrors = 0    // Fail on any error
    source(project.sourceSets.main.get().allSource.matching {
        exclude("**/*.psd", "**/*.PSD")
    })
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

var stagingFolder = File(project.layout.buildDirectory.get().toString(), "staging")

dependencies {
    implementation("com.puppycrawl.tools:checkstyle:12.3.1")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

tasks.register<Zip>("unitFilesZip") {
    description = "Creates zip archives of all the unit file folders (excluding loose .txt and .xml files)."
    group = "build"
    destinationDirectory.set(File(stagingFolder, "mekfiles"))
    archiveFileName.set("unit_files.zip")
    from("data/mekfiles") {
        exclude("*.txt")
        exclude("*.xml")
        exclude("*.cache")
    }
}

tasks.register<Zip>("ratZip") {
    description = "Creates a zip archive of all the random assignment tables."
    group = "build"
    from("data/rat")
    destinationDirectory.set(File(stagingFolder, "rat"))
    archiveFileName.set("rat_default.zip")
}

tasks.register<Zip>("canonSystemZip") {
    description = "Creates a zip archive of canon planetary systems."
    group = "build"
    from("data/universe/planetary_systems/canon_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("canon_systems.zip")
}

tasks.register<Zip>("connectorSystemZip") {
    description = "Creates a zip archive of connector systems planetary systems."
    group = "build"
    from("data/universe/planetary_systems/connector_systems/")
    destinationDirectory.set(File(stagingFolder, "universe/planetary_systems"))
    archiveFileName.set("connector_systems.zip")
}

tasks.register<Copy>("stageMMFiles") {
    description = "Stages files for MM"
    group = "build"

    dependsOn("ratZip")
    dependsOn("unitFilesZip")

    from("data") {
        include("boards/**/*.*")
        include("css/**/*.*")
        include("fonts/**/*.*")
        include("forcegenerator/**/*.*")
        include("images/camo/**/*.*")
        include("images/fluff/**/*.*")
        include("images/hexes/**/*.*")
        include("images/misc/**/*.*")
        include("images/portraits/**/*.*")
        include("images/temp/**/*.*")
        include("images/units/**/*.*")
        include("images/universe/**/*.*")
        include("images/widgets/**/*.*")
        include("mapgen/**/*.*")
        include("mapsetup/**/*.*")
        include("mekfiles/*.txt")
        include("mekfiles/*.xml")
        exclude("mekfiles/*.cache")
        include("names/**/*.*")
        include("scenarios/**/*.*")
        include("sounds/**/*.*")
        include("sourcebooks/*.*")
        include("universe/eras.xml")
        include("universe/commands/**/*.*")
        include("universe/factions/**/*.*")
    }

    from(stagingFolder) {
        include("mekfiles/**/*.*")
        include("rat/**/*.*")
        exclude("mekfiles/*.cache")
    }

    into("${stagingFolder}/mm")
}

tasks.register<Copy>("stageMMLFiles") {
    description = "Stages files for MML"
    group = "build"

    mustRunAfter("ratZip")
    mustRunAfter("unitFilesZip")
    dependsOn("ratZip")
    dependsOn("unitFilesZip")

    from("data") {
        include("fonts/**/*.*")
        include("forcegenerator/**/*.*")
        include("images/fluff/**/*.*")
        include("images/misc/**/*.*")
        include("images/recordsheets/**/*.*")
        include("images/units/**/*.*")
        include("images/universe/**/*.*")
        include("images/widgets/**/*.*")
        include("mekfiles/*.txt")
        include("mekfiles/*.xml")
        exclude("mekfiles/*.cache")
        include("names/**/*.*")
        include("sourcebooks/*.*")
        include("universe/commands/**/*.*")
        include("universe/factions/**/*.*")
        include("universe/eras.xml")
    }

    from(stagingFolder) {
        include("mekfiles/**/*.*")
        include("rat/**/*.*")
        exclude("mekfiles/*.cache")
    }

    into("${stagingFolder}/mml")
}

tasks.register<Copy>("stageFiles") {
    description = "Stages files for All / MekHQ"
    group = "build"

    mustRunAfter("ratZip")
    mustRunAfter("unitFilesZip")
    mustRunAfter("canonSystemZip")
    mustRunAfter("connectorSystemZip")
    dependsOn("ratZip")
    dependsOn("unitFilesZip")
    dependsOn("canonSystemZip")
    dependsOn("connectorSystemZip")

    from("data/mekfiles") {
        include("*.txt")
        include("*.xml")
        into("mekfiles")
    }

    from("data") {
        exclude("mekfiles")
        exclude("rat")
        exclude("universe/planetary_systems/canon_systems")
        exclude("universe/planetary_systems/connector_systems")
        include("**/*.*")
    }

    from(stagingFolder) {
        include("mekfiles/**/*.*")
        exclude("mekfiles/*.cache")
        include("rat/**/*.*")
        include("universe/**/*.*")
    }

    into("${stagingFolder}/all")
}
